--------------------------------------------------------
--  DDL for Index PK_NOTICE_FILE_IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "GZONE"."PK_NOTICE_FILE_IDX" ON "GZONE"."NOTICE_FILE" ("NOTICE_FILE_IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
