REM INSERTING into GZONE.ACCOUNT_MANAGEMENT
SET DEFINE OFF;
Insert into GZONE.ACCOUNT_MANAGEMENT (ACC_IDX,TOWN_IDX,ACC_ACCOUNT_NUM,ACC_BANK,ACC_DEPOSITOR) values (1,1,'54616546-456543213','우리','김부자');
