REM INSERTING into GZONE.CLOSED_DAY
SET DEFINE OFF;
Insert into GZONE.CLOSED_DAY (CLOSED_IDX,TOUR_IDX,CLOSED_START_DATE,CLOSED_END_DATE,CLOSED_CONTENT) values (1,1,to_date('20/07/28','RR/MM/DD'),to_date('20/07/30','RR/MM/DD'),'7월 28일 ~ 30일 코로나로 휴무						 		
				 			');
