REM INSERTING into GZONE.COMENT
SET DEFINE OFF;
Insert into GZONE.COMENT (COMENT_IDX,REVIEW_IDX,MEMBER_IDX,COMENT_CONTENT,COMENT_EMOTICON,COMENT_CRE_DATE,COMENT_MOD_DATE,COMENT_DEL_YN) values (1,1,1,'댓글달았따','smile',to_date('20/07/15','RR/MM/DD'),to_date('20/07/15','RR/MM/DD'),'n');
