--------------------------------------------------------
--  Constraints for Table ACCOUNT_MANAGEMENT
--------------------------------------------------------

  ALTER TABLE "GZONE"."ACCOUNT_MANAGEMENT" ADD CONSTRAINT "PK_ACC_IDX" PRIMARY KEY ("ACC_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GZONE"."ACCOUNT_MANAGEMENT" MODIFY ("ACC_DEPOSITOR" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."ACCOUNT_MANAGEMENT" MODIFY ("ACC_BANK" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."ACCOUNT_MANAGEMENT" MODIFY ("ACC_ACCOUNT_NUM" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."ACCOUNT_MANAGEMENT" MODIFY ("TOWN_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."ACCOUNT_MANAGEMENT" MODIFY ("ACC_IDX" NOT NULL ENABLE);
