--------------------------------------------------------
--  Constraints for Table CLOSED_DAY
--------------------------------------------------------

  ALTER TABLE "GZONE"."CLOSED_DAY" ADD CONSTRAINT "PK_CLOSED_IDX" PRIMARY KEY ("CLOSED_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GZONE"."CLOSED_DAY" MODIFY ("CLOSED_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."CLOSED_DAY" MODIFY ("CLOSED_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."CLOSED_DAY" MODIFY ("TOUR_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."CLOSED_DAY" MODIFY ("CLOSED_IDX" NOT NULL ENABLE);
