--------------------------------------------------------
--  Constraints for Table COMENT
--------------------------------------------------------

  ALTER TABLE "GZONE"."COMENT" ADD CONSTRAINT "PK_COMENT_IDX" PRIMARY KEY ("COMENT_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GZONE"."COMENT" MODIFY ("COMENT_DEL_YN" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."COMENT" MODIFY ("COMENT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."COMENT" MODIFY ("MEMBER_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."COMENT" MODIFY ("REVIEW_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."COMENT" MODIFY ("COMENT_IDX" NOT NULL ENABLE);
