--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "GZONE"."COURSE" ADD CONSTRAINT "PK_COURSE_IDX" PRIMARY KEY ("COURSE_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GZONE"."COURSE" MODIFY ("COURSE_NAME" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."COURSE" MODIFY ("TOWN_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."COURSE" MODIFY ("COURSE_IDX" NOT NULL ENABLE);
