--------------------------------------------------------
--  Constraints for Table NOTICEBOARD
--------------------------------------------------------

  ALTER TABLE "GZONE"."NOTICEBOARD" ADD CONSTRAINT "PK_NOTICE_IDX" PRIMARY KEY ("NOTICE_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GZONE"."NOTICEBOARD" MODIFY ("NOTICE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."NOTICEBOARD" MODIFY ("NOTICE_TITLE" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."NOTICEBOARD" MODIFY ("MEMBER_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."NOTICEBOARD" MODIFY ("NOTICE_IDX" NOT NULL ENABLE);
