--------------------------------------------------------
--  Constraints for Table RESERVE
--------------------------------------------------------

  ALTER TABLE "GZONE"."RESERVE" ADD CONSTRAINT "PK_RESERVE_IDX" PRIMARY KEY ("RESERVE_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GZONE"."RESERVE" MODIFY ("RESERVE_DEPOSIT_STATE" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."RESERVE" MODIFY ("RESERVE_PRICE" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."RESERVE" MODIFY ("RESERVE_APPLY_NUM" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."RESERVE" MODIFY ("RESERVE_TOUR_DATE" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."RESERVE" MODIFY ("MEMBER_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."RESERVE" MODIFY ("TOUR_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."RESERVE" MODIFY ("RESERVE_IDX" NOT NULL ENABLE);
