--------------------------------------------------------
--  Constraints for Table REVIEW_FILE
--------------------------------------------------------

  ALTER TABLE "GZONE"."REVIEW_FILE" ADD CONSTRAINT "PK_REVIEW_FILE_IDX" PRIMARY KEY ("REVIEW_FILE_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GZONE"."REVIEW_FILE" MODIFY ("REVIEW_STORED_FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."REVIEW_FILE" MODIFY ("REVIEW_ORIGINAL_FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."REVIEW_FILE" MODIFY ("REVIEW_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."REVIEW_FILE" MODIFY ("REVIEW_FILE_IDX" NOT NULL ENABLE);
