--------------------------------------------------------
--  Constraints for Table REVIEWBOARD
--------------------------------------------------------

  ALTER TABLE "GZONE"."REVIEWBOARD" ADD CONSTRAINT "PK_REVIEW_IDX" PRIMARY KEY ("REVIEW_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GZONE"."REVIEWBOARD" MODIFY ("REVIEW_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."REVIEWBOARD" MODIFY ("REVIEW_TITLE" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."REVIEWBOARD" MODIFY ("COURSE_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."REVIEWBOARD" MODIFY ("MEMBER_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."REVIEWBOARD" MODIFY ("REVIEW_IDX" NOT NULL ENABLE);
