--------------------------------------------------------
--  Constraints for Table REVIEW_COMMENT
--------------------------------------------------------

  ALTER TABLE "GZONE"."REVIEW_COMMENT" ADD CONSTRAINT "PK_COMMENT_IDX" PRIMARY KEY ("COMMENT_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GZONE"."REVIEW_COMMENT" MODIFY ("COMMENT_DEL_YN" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."REVIEW_COMMENT" MODIFY ("COMMENT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."REVIEW_COMMENT" MODIFY ("MEMBER_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."REVIEW_COMMENT" MODIFY ("REVIEW_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."REVIEW_COMMENT" MODIFY ("COMMENT_IDX" NOT NULL ENABLE);
