--------------------------------------------------------
--  Constraints for Table TOUR
--------------------------------------------------------

  ALTER TABLE "GZONE"."TOUR" ADD CONSTRAINT "UK_TOUR_NAME" UNIQUE ("TOUR_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GZONE"."TOUR" ADD CONSTRAINT "PK_TOUR_IDX" PRIMARY KEY ("TOUR_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GZONE"."TOUR" MODIFY ("TOUR_DEL_YN" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOUR" MODIFY ("TOUR_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOUR" MODIFY ("TOUR_STARTING_POINT" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOUR" MODIFY ("TOUR_PEOPLE_NUM" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOUR" MODIFY ("TOUR_PRICE" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOUR" MODIFY ("TOUR_END_TIME" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOUR" MODIFY ("TOUR_START_TIME" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOUR" MODIFY ("TOUR_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOUR" MODIFY ("TOUR_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOUR" MODIFY ("TOUR_NAME" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOUR" MODIFY ("TOWN_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOUR" MODIFY ("TOUR_IDX" NOT NULL ENABLE);
