--------------------------------------------------------
--  Constraints for Table TOWN
--------------------------------------------------------

  ALTER TABLE "GZONE"."TOWN" ADD CONSTRAINT "UK_TOWN_NAME" UNIQUE ("TOWN_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GZONE"."TOWN" ADD CONSTRAINT "PK_TOWN_IDX" PRIMARY KEY ("TOWN_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GZONE"."TOWN" MODIFY ("TOWN_DEL_YN" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOWN" MODIFY ("TOWN_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOWN" MODIFY ("TOWN_NAME" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOWN" MODIFY ("TOWN_IDX" NOT NULL ENABLE);
