--------------------------------------------------------
--  Constraints for Table TOWN_MANAGEMENT
--------------------------------------------------------

  ALTER TABLE "GZONE"."TOWN_MANAGEMENT" ADD CONSTRAINT "PK_MANAGE_IDX" PRIMARY KEY ("MANAGE_IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GZONE"."TOWN_MANAGEMENT" MODIFY ("MANAGE_GRADE" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOWN_MANAGEMENT" MODIFY ("TOWN_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOWN_MANAGEMENT" MODIFY ("MEMBER_IDX" NOT NULL ENABLE);
  ALTER TABLE "GZONE"."TOWN_MANAGEMENT" MODIFY ("MANAGE_IDX" NOT NULL ENABLE);
