--------------------------------------------------------
--  DDL for Table COMENT
--------------------------------------------------------

  CREATE TABLE "GZONE"."COMENT" 
   (	"COMENT_IDX" NUMBER, 
	"REVIEW_IDX" NUMBER, 
	"MEMBER_IDX" NUMBER, 
	"COMENT_CONTENT" VARCHAR2(4000 BYTE), 
	"COMENT_EMOTICON" VARCHAR2(10 BYTE) DEFAULT 'smile', 
	"COMENT_CRE_DATE" DATE DEFAULT SYSDATE, 
	"COMENT_MOD_DATE" DATE DEFAULT SYSDATE, 
	"COMENT_DEL_YN" VARCHAR2(1 BYTE) DEFAULT 'n'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
