--------------------------------------------------------
--  DDL for Table NOTICEBOARD
--------------------------------------------------------

  CREATE TABLE "GZONE"."NOTICEBOARD" 
   (	"NOTICE_IDX" NUMBER, 
	"MEMBER_IDX" NUMBER, 
	"NOTICE_TITLE" VARCHAR2(100 BYTE), 
	"NOTICE_CONTENT" VARCHAR2(4000 BYTE), 
	"NOTICE_CRE_DATE" DATE DEFAULT SYSDATE, 
	"NOTICE_MOD_DATE" DATE DEFAULT SYSDATE, 
	"NOTICE_FIXED" VARCHAR2(5 BYTE) DEFAULT 'none'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
