--------------------------------------------------------
--  DDL for Table REVIEW_COMMENT
--------------------------------------------------------

  CREATE TABLE "GZONE"."REVIEW_COMMENT" 
   (	"COMMENT_IDX" NUMBER, 
	"REVIEW_IDX" NUMBER, 
	"MEMBER_IDX" NUMBER, 
	"COMMENT_CONTENT" VARCHAR2(4000 BYTE), 
	"COMMENT_EMOTICON" VARCHAR2(10 BYTE) DEFAULT 'smile', 
	"COMMENT_CRE_DATE" DATE DEFAULT SYSDATE, 
	"COMMENT_MOD_DATE" DATE DEFAULT SYSDATE, 
	"COMMENT_DEL_YN" VARCHAR2(1 BYTE) DEFAULT 'n'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
