--------------------------------------------------------
--  DDL for Table REVIEWBOARD
--------------------------------------------------------

  CREATE TABLE "GZONE"."REVIEWBOARD" 
   (	"REVIEW_IDX" NUMBER, 
	"MEMBER_IDX" NUMBER, 
	"COURSE_IDX" NUMBER, 
	"REVIEW_TITLE" VARCHAR2(150 BYTE), 
	"REVIEW_CONTENT" VARCHAR2(4000 BYTE), 
	"REVIEW_CRE_DATE" DATE DEFAULT SYSDATE, 
	"REVIEW_MOD_DATE" DATE DEFAULT SYSDATE, 
	"REVIEW_READ_COUNT" NUMBER DEFAULT 0, 
	"REVIEW_LIKE_COUNT" NUMBER DEFAULT 0, 
	"REVIEW_RATING" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
