--------------------------------------------------------
--  DDL for Table TOUR
--------------------------------------------------------

  CREATE TABLE "GZONE"."TOUR" 
   (	"TOUR_IDX" NUMBER, 
	"TOWN_IDX" NUMBER, 
	"TOUR_NAME" VARCHAR2(100 BYTE), 
	"TOUR_START_DATE" DATE DEFAULT SYSDATE, 
	"TOUR_END_DATE" DATE DEFAULT SYSDATE, 
	"TOUR_START_TIME" VARCHAR2(20 BYTE) DEFAULT '00:00', 
	"TOUR_END_TIME" VARCHAR2(20 BYTE) DEFAULT '23:59', 
	"TOUR_PRICE" NUMBER DEFAULT 0, 
	"TOUR_PEOPLE_NUM" NUMBER, 
	"TOUR_STARTING_POINT" VARCHAR2(350 BYTE), 
	"TOUR_CONTENT" VARCHAR2(4000 BYTE), 
	"TOUR_DEL_YN" VARCHAR2(1 BYTE) DEFAULT 'n', 
	"TOUR_CRE_DATE" DATE DEFAULT SYSDATE, 
	"TOUR_MOD_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "GZONE"."TOUR"."TOUR_IDX" IS '투어번호';
   COMMENT ON COLUMN "GZONE"."TOUR"."TOWN_IDX" IS '마을번호';
   COMMENT ON COLUMN "GZONE"."TOUR"."TOUR_NAME" IS '투어명';
   COMMENT ON COLUMN "GZONE"."TOUR"."TOUR_START_DATE" IS '시작일';
   COMMENT ON COLUMN "GZONE"."TOUR"."TOUR_END_DATE" IS '종료일';
   COMMENT ON COLUMN "GZONE"."TOUR"."TOUR_START_TIME" IS '시작시간';
   COMMENT ON COLUMN "GZONE"."TOUR"."TOUR_END_TIME" IS '종료시간';
   COMMENT ON COLUMN "GZONE"."TOUR"."TOUR_PRICE" IS '가격';
   COMMENT ON COLUMN "GZONE"."TOUR"."TOUR_PEOPLE_NUM" IS '모집인원';
   COMMENT ON COLUMN "GZONE"."TOUR"."TOUR_STARTING_POINT" IS '출발지';
   COMMENT ON COLUMN "GZONE"."TOUR"."TOUR_CONTENT" IS '소개내용';
   COMMENT ON COLUMN "GZONE"."TOUR"."TOUR_CRE_DATE" IS '등록일';
   COMMENT ON COLUMN "GZONE"."TOUR"."TOUR_MOD_DATE" IS '수정일';
   COMMENT ON TABLE "GZONE"."TOUR"  IS '투어 테이블';
