--------------------------------------------------------
--  DDL for Table TOUR_FILE
--------------------------------------------------------

  CREATE TABLE "GZONE"."TOUR_FILE" 
   (	"TOUR_FILE_IDX" NUMBER, 
	"TOUR_IDX" NUMBER, 
	"TOUR_ORIGINAL_FILE_NAME" VARCHAR2(300 BYTE), 
	"TOUR_STORED_FILE_NAME" VARCHAR2(300 BYTE), 
	"TOUR_FILE_SIZE" NUMBER DEFAULT 0, 
	"TOUR_FILE_CRE_DATE" DATE DEFAULT SYSDATE, 
	"TOUR_FILE_MOD_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
