--------------------------------------------------------
--  DDL for Table TOWN_MANAGEMENT
--------------------------------------------------------

  CREATE TABLE "GZONE"."TOWN_MANAGEMENT" 
   (	"MANAGE_IDX" NUMBER, 
	"MEMBER_IDX" NUMBER, 
	"TOWN_IDX" NUMBER, 
	"MANAGE_GRADE" VARCHAR2(10 BYTE) DEFAULT 'manager'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
